name: CI CD pipeline
on: 
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  actions: write
  issues: write
  checks: write
 
jobs:
  upload-performance-report:
        runs-on: ubuntu-24.04
        env:
            BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        
        steps:
        - name: Checkout code
          uses: actions/checkout@v3
          with:
              ref: ${{ env.BRANCH_NAME }}  # Ensure you are checking out the correct branch
              clean: true
        - name: Upload test results
          uses: actions/upload-artifact@v4
          with:
             name: junit-test-results
             path: ${{ github.workspace }}/hybris/bin/custom/response.xml
             
  visualize-performance-report:
        runs-on: ubuntu-24.04
        outputs:
            test_time: ${{ steps.test_case_status.outputs.test_duration }}
        needs: upload-performance-report 
        steps:
        - name: Checkout code
          uses: actions/checkout@v3
          with:
              ref: ${{ env.BRANCH_NAME }}  # Ensure you are checking out the correct branch
              clean: true
        - name: Download JUnit XML artifact
          uses: actions/download-artifact@v4
          with:
             name: junit-test-results

        - name: Install xmlstarlet
          run: sudo apt-get update && sudo apt-get install -y xmlstarlet
          
        - name: Fail test case if duration > 20 sec
          id: test_case_status
          run: |
            #!/bin/bash
            # Parse the JUnit XML and check each test case duration
            xmlstarlet sel -t -m "//testsuite/testcase" -v "@name" -o " took " -v "@time" -n ${{ github.workspace }}/hybris/bin/custom/response.xml | while read line; do
              test_name=$(echo $line | cut -d' ' -f1)
              test_duration=$(echo $line | cut -d' ' -f3)
              # Check if any test took more than 20 seconds
              if (( $(echo "$test_duration > 20" | bc -l) )); then
                echo "Test case '$test_name' took ${test_duration} seconds, which is more than the 20-second limit."
                echo "test_duration=false" >> $GITHUB_ENV
              fi
            done
            echo "Test Status: $test_duration"
            echo "TEST_DURATION=$test_duration" >> $GITHUB_ENV
        - name: Send email
          if: env.test_duration == 'false'
          uses: dawidd6/action-send-mail@v3
          with:
             server_address: smtp.gmail.com
             server_port: 465
             secure: false
             ignore_cert: true
             subject: "Performance test is failed"
             to: ramesh.kumar.simma@accenture.com
             cc: ramesh.kumar.simma@accenture.com
             from: ramesh.kumar.simma@accenture.com
             attachments: ${{ github.workspace }}/hybris/bin/custom/response.xml
             body: |            
                      
        - name: JUnite Test Report
          uses: dorny/test-reporter@v1
          with:
             name: junit-test-results
             path: ${{ github.workspace }}/hybris/bin/custom/response.xml
             reporter: java-junit
             fail-on-error: false
             
        - name: Set Job Status
          id: set_status
          if: always()  # Ensure this step always runs
          run: |
            if [ "${{ job.status }}" == "success" ]; then
              echo "Job succeeded"
              echo "::set-output name=job_status::SUCCESS"
            else
              echo "Job failed"
              echo "::set-output name=job_status::FAIL"
            fi
          shell: bash
